repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6

-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: master
    hooks:
    - id: pylint
      args: [--rcfile, .pylintrc-precommit.ini]